version: "3"

services:
  web:
    image: nexblu/illustra-line-api:24.7.6
    ports:
      - "5000"
    depends_on:
      - db
    environment:
      - POSTGRESQL_URL=postgresql://postgres:postgres@db/IllustraLine
    volumes:
      - .:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: IllustraLine
    ports:
      - "5432"
